-   id: pip-compile
    name: pip-compile
    description: "generates requirements.txt file from requirements.in file using pip-compile"
    language: script
    entry: hooks/pip-compile
    files: "^requirements.(?:in|txt)$"

-   id: pip-compile-multi
    name: pip-compile-multi
    description: "generates all requirements.txt files from all requirements.in files using pip-compile"
    language: script
    entry: hooks/pip-compile-multi
    files: "^.*requirements.(?:in|txt)$"

-   id: make-migrations
    name: make-migrations
    description: "ensures no Django model migrations were forgotten to be made"
    language: script
    entry: hooks/make-migrations
    files: ".+.py"
